#!/usr/bin/env python3
"""Generate a read-only report for remote branches and their open PRs."""

from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPOSITORY = "aungmyat1/ag-edgelab"
OUTPUT = ROOT / "docs" / "governance" / "branch_inventory.md"

OBSOLETE = {
    "feat/fx-cycle2-breakout",
    "feat/fx-asian-sweep-candidate",
    "feat/fx-edge-candidate",
    "feat/fx-lny-candidate",
    "feat/crypto-btc-breakout-candidate",
    "feat/crypto-btc-h1-candidate",
}
SALVAGE = {
    "feat/crypto-btc-spot-candidate",
    "feat/crypto-btc-economic-verification",
    "feat/r2-robustness",
    "feat/strategy-verification",
}
PARKED = {"feat/r1-nautilus-adapter"}


@dataclass(frozen=True)
class BranchRecord:
    name: str
    classification: str
    ahead: int
    open_prs: tuple[tuple[int, str], ...]


def run(command: list[str]) -> str:
    return subprocess.run(
        command, cwd=ROOT, check=True, capture_output=True, text=True
    ).stdout


def remote_branch_names(refs: list[str]) -> list[str]:
    return sorted(
        ref.removeprefix("origin/")
        for ref in refs
        if ref.startswith("origin/") and ref != "origin/HEAD"
    )


def classify_branch(name: str, ahead: int) -> str:
    if name == "main":
        return "ACTIVE"
    if ahead == 0:
        return "MERGED"
    if name in OBSOLETE:
        return "OBSOLETE"
    if name in SALVAGE:
        return "SALVAGE"
    if name in PARKED:
        return "PARKED"
    return "ACTIVE"


def open_pull_requests() -> dict[str, tuple[tuple[int, str], ...]]:
    result = run([
        "gh", "pr", "list", "--repo", REPOSITORY, "--state", "open",
        "--limit", "1000", "--json", "headRefName,number,url",
    ])
    prs = json.loads(result)
    grouped: dict[str, list[tuple[int, str]]] = {}
    for pull_request in prs:
        grouped.setdefault(pull_request["headRefName"], []).append(
            (pull_request["number"], pull_request["url"])
        )
    return {
        branch: tuple(sorted(branch_prs))
        for branch, branch_prs in grouped.items()
    }


def collect_records() -> list[BranchRecord]:
    refs = run([
        "git", "for-each-ref", "--format=%(refname:short)",
        "refs/remotes/origin",
    ]).splitlines()
    prs_by_branch = open_pull_requests()
    records = []
    for branch in remote_branch_names(refs):
        ahead = int(run([
            "git", "rev-list", "--count", f"origin/main..origin/{branch}"
        ]).strip())
        records.append(BranchRecord(
            name=branch,
            classification=classify_branch(branch, ahead),
            ahead=ahead,
            open_prs=prs_by_branch.get(branch, ()),
        ))
    return records


def render_report(records: list[BranchRecord]) -> str:
    lines = [
        "# Remote Branch Inventory",
        "",
        f"Remote branches: **{len(records)}** (remote heads only; excludes `HEAD`).",
        "",
        "Generated by `scripts/branch_hygiene_report.py`. This report does not",
        "modify branches or tags.",
        "",
        "| Branch | Classification | Commits ahead of `origin/main` | Open PR |",
        "| --- | --- | ---: | --- |",
    ]
    for record in records:
        open_prs = ", ".join(
            f"[#{number}]({url})" for number, url in record.open_prs
        ) or "None"
        lines.append(
            f"| `{record.name}` | {record.classification} | "
            f"{record.ahead} | {open_prs} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    report = render_report(collect_records())
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(report, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())